<?php

/**
 * Implements hook_menu().
 */
function drupal_training_menu() {
  $items = array();

  $items['hello-world'] = array(
    'title' => 'Hello world',
    'access callback' => TRUE,
    'page callback' => 'drupal_training_hello_world',
    'file' => 'drupal_training.pages.inc',
    'type' => MENU_CALLBACK,
  );
  
  $items['node/%node/hello­form'] = array(
    'title' => 'Hello forms',
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupal_training_hello_form', 1),
    'file' => 'drupal_training.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_node_view().
 */
function drupal_training_node_view($node, $view_mode, $langcode) {
  if ($node­>type == 'article' && !$node­>status) {
    drupal_set_message(t('You are viewing the draft of an
article.'));
  }
}

function drupal_training_block_info() {
  $blocks['my_block'] = array(
    'info' => t('My Drupal Training block'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().  */
function drupal_training_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'my_block':
      $block['subject'] = t('Block title');
      $block['content'] = t('Hello world');
      break;
  }

  return $block;
}
